### PR TITLE
[Enhancement] Configure CFF (#8)

### LINKED ISSUE #1529: Discussion:  CFF Data
> This issue originates from #1523.

As I announced in #1523, this is the issue for the discussion of the initial CFF meta data.

The setup will include:

- the CITATION.cff;
- a GitHub Action for automatic validation; and
- a badge for the README referring to the CFF validation Action.

Most of the meta data is obvious.  I only need the following information in order to prepare the Pull Request:

- author information:  @fox0430, I would initially add you as the sole author and only with your GitHub alias.  Many projects handle the authorship in terms of CFF differently; some consider it a list of contributors, others limit it the original author, some add the project's community as the anonymous group who co-authored the project.  Which option would you prefer?
- artifact repository:  is there any website which stores precompiled binaries of Moe?

The list of references can be curated on demand once the setup is completed.

A note on the maintenance effort:  the release date as well as the version need to be updated on release.  These are two succeeding lines in the CITATION.cff.  I can also add an automation to increment the version numbers on release; unfortunately, it does not support release dates, as far as I know.

### PR DESCRIPTION
**Pull request by kevinmatthes**
This PR fixes #1529.  I added all recent contributors only with their GitHub aliases, sorted according to the list of contributors at the time of this writing.

### CODE REVIEW

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you!

**Comment by kevinmatthes** [comment]
@fox0430

As Moe now both supports syntax highlighting for CFF (using YAML redirection) as well as it is CFF-citable, we could ask the CFF team for integration to the tooling catalogue.  This might take a while but as far as I know, Moe would be the very first editor which supports the Citation File Format out-of-the-box.

**Comment by kevinmatthes** [comment]
@fox0430, would you like to have the privilege of asking for integration to the CFF repository's tooling table or shall I ask for integration?

https://github.com/citation-file-format/citation-file-format/issues/new/choose ("Tool idea" issue template)

**Comment by fox0430** [comment]
@kevinmatthes 

if you can do that, please.

**Comment by kevinmatthes** [comment]
@fox0430 https://github.com/citation-file-format/citation-file-format/issues/419

**Comment by fox0430** [comment]
@kevinmatthes 

Thank you!

**Pull request merged**
