### PR TITLE
v0.2.1

### PR DESCRIPTION
**Pull request by fox0430**
Add supports for Python and JavaScript syntax highlighting
Add QuickRun support
Add Recent files selection support
Add Automatic backups support

Show error message if including the invalid setting in the configuration file

Improve syntax highlighting performance
Don't highlight whitespaces at end of the line in the current line

Improve auto indent

Fix replace mode behavior

Normal mode: Add ```dG``` command (Delete the line from the current line to last lines)
Normal mode: Add ```\n``` command (QuickRun)

Visual block mode: Add ```Shift+i``` command (Insert character multiple lines)

Ex mode: Make commands case insensitive
Ex mode: Add ```Q``` and ```run``` commands (QuickRun) 
Ex mode: Add ```lsw``` command (Show all workspace)

Workspace: Show error message if select not exist workspace

Settings: Add ```Notifications``` setting
Settings: Add ```StatusBar.showModeInactive``` (Setting to show/hidden mode label in the status bar when the window is inactive)
Settings: Add ```disableChangeCursor``` setting (Disable the change of the cursor shape)
Settings: Add ```Theme.gtPreprocessor``` setting
Settings: Change setting name from ```realtimeSearch``` to ```incrementalSearch```
Settings: Change setting name from ```BuildOnSaveSettings.buidOSave``` to ```BuildOnSaveSettings.enable```
Settings: Change setting name from ```WorkSpace.useBar``` to ```WorkSpace.workSpaceLine```

Fix and add unit tests

Fix: Crash when delete buffer in visual mode
Fix: When a window is a vertical split, a new window is always added to the far right
Fix: Visual and command mode messages
Fix: Unhandled exception when deleting buffer in normal mode
Fix: Unhandled exception when opening /mnt/c/Users/ in WSL
Fix: Standard.popUpWindowInExmode setting not working
Fix: ExMode changes only after putting a char
Fix: Standard.popUpWindowInExmode setting not working
Fix: Targets of symbolic links are not displayed in filer mode
Fix: Not yank character when using x command in normal mode
Fix: Crash when using x in visual block mode with more than one column selected
Fix: Crash when deleting a current character in visual mode
Fix: Unhandled exception when opening /dev/fd/
Fix: Symbolic links that failed to be expanded show up as empty strings in filer mode
Fix: Hangs when opening a directory containing named pipes in filer mode
Fix: Log is not displayed when opening the log viewer 
Fix: Ex mode ```q``` command exits editor even if there are unsaved buffers in other workspaces
Fix: BuildOnSave.command settings not working
Fix: Some color settings in Theme not working
Fix: Broken highlight in visual block mode

### CODE REVIEW

**Comment by tobimensch** [comment]
@fox0430 
You put a huge amount of work into this release!

Amazing! Thank you!

**Comment by fox0430** [comment]
@tobimensch 

v0.2.1 is a very exciting release!
Thank you for your contribution!

**Comment by tobimensch** [comment]
Can't wait to see this release being done. Want to recommend moe to some people again, this release will definitely show moe's potential better than any of the ones that came before.

**Comment by fox0430** [comment]
@tobimensch 

I can't wait too! Please wait a little longer.

**Pull request merged**
