### PR TITLE
Initial VSCode Theme support - Implement #646

### PR DESCRIPTION
**Pull request by tobimensch**
This was only tested against the Forest Focus theme for VSCode/VSCodium,
and was made to approximate the theme, not to imitate it perfectly,  (this is work in progress).
There are some rough corners.

It might work fine with other VSCode themes, but it's untested so far.
Help appreciated!

The vscode theme can be detected automatically, but support for this was
only tested on Linux. For this you simply set "vscode" as the theme in
the Standard section of the config.
You can set the baseTheme setting of the Theme section in the config
to a VSCode theme file and set the theme in the Standard section to "config",
this should work on all systems.

I created a macro named setEditorColor, that should make it relatively easy to
fix the code for more themes.
Here's one example:
```
    setEditorColor searchResult:
      foreground:
        adjust: ReadableVsBackground
      background:
        colorFromNode(jsonNode{"colors", "tab.activeBorder"})
```
As you can see "tab.activeBorder" is used for the background of search results,
which is a very creative mapping of colors from VSCode to moe, that randomly
works for the Forest Focus theme (and my taste), but will probably fail for other
themes. "adjust: ReadableVsBackground" ensures, that foreground colors are
readable compared to their background by doing some "magic" calculations and
adjusting the foreground color.
If we find some other VSCode theme properties that work better for a great number
of themes, they should be put first in the respective foreground/background lists,
as every statement there that doesn't return Color.default will be deemed a success,
and will thus be used to set that color.
Example:
```
    setEditorColor searchResult:
      foreground:
        colorFromNode(jsonNode{"colors", "some.betterForegroundForSearch"})
        adjust: ReadableVsBackground
      background:
        colorFromNode(jsonNode{"colors", "some.betterBackgroundForSearch"})
        colorFromNode(jsonNode{"colors", "tab.activeBorder"})
```
With these changes (but first we would have to know what that better property is!),
"tab.activeBorder" will simply be ignored, for all VSCode theme files, that contain
"some.betterBackgroundForSearch". And if "some.betterBackgroundForSearch" is
missing (like in Forest Focus) "tab.activeBorder" would be used as a fallback.

You can ask me anything.

### CODE REVIEW

**Comment by fox0430** [comment]
@tobimensch 

Excellent work!
Thank you for your PR!

**Comment by fox0430** [comment]
@tobimensch 

Can I write documentation?
You don't have to do a perfect job.

**Comment by tobimensch** [comment]
@fox0430 
All help is much appreciated. :-)

**Comment by fox0430** [comment]
@tobimensch 

I can not set theme...
This config is incorrect?

### ~/.config/moe/moerc.toml
```
[Standard]

theme = "vscode"
```

VS Code theme is Forest Focus.

**Comment by tobimensch** [comment]
Yes, that should work.

What system are you running this one?

Do you have VSCode or VSCodium?

**Comment by fox0430** [comment]
@tobimensch 

I'm using VSCode on Arch Linux.

**Comment by tobimensch** [comment]
@fox0430 
I pushed another commit. Please try again, I set the wrong directory for VSCode.

**Comment by fox0430** [comment]
It works! Thank you.

**Pull request merged**
