### PR TITLE
Fix before job #1129

### PR DESCRIPTION
**Pull request by jiro4989**

### CODE REVIEW

**Comment by jiro4989** [comment]
Ah, wait

**Comment by jiro4989** [comment]
CI may fail again when commit message has `"` (double quote).

**Comment by jiro4989** [comment]
```bash
echo -e "foobar "

"
```

**Comment by jiro4989** [comment]
umm

**Comment by jiro4989** [comment]
Removed printing commit message.

**Comment by fox0430** [comment]
@jiro4989 

Ok. Thanks!

**Pull request merged**
