### PR TITLE
Add support for Python highlighting

### PR DESCRIPTION
**Pull request by unihernandez22**

### CODE REVIEW

**Comment by fox0430** [comment]
@unihernandez22 

Can you include the content of a copying.txt of a Nim repo in a highlite.nim (MIT license) ?

https://github.com/nim-lang/Nim/blob/devel/copying.txt

**Comment by walkre-niboshi** [comment]
I guess we need to include the MIT license text in highlite.nim. However, to be honest, I'm not confident because I'm not familiar with software licenses. So I'm sorry if I made a mistake. I would be grateful if someone familiar with it could teach me.

**Comment by unihernandez22** [comment]
@fox0430 
> Can you include the content of a copying.txt of a Nim repo in a highlite.nim (MIT license) ?

Done

**Comment by fox0430** [comment]
@unihernandez22 

Great. Thank you.

**Pull request merged**
